import type { Reservation, Client, Partner, Supplier, DashboardStats, Itinerary, Guide, GuideAssignment, Vehicle, Driver, SupplierBooking, CostLine } from '@/types';

export const mockClients: Client[] = [
  {
    id: 'c1',
    full_name: 'James & Sophie Whitfield',
    email: 'james.whitfield@gmail.com',
    phone: '+44 7700 900123',
    whatsapp: '+44 7700 900123',
    nationality: 'British',
    passport_number: 'GB123456',
    is_vip: true,
    is_repeat_client: false,
    special_occasions: ['honeymoon'],
    notes: 'First trip to Sri Lanka. Prefer boutique properties.',
    created_at: '2025-12-01T10:00:00Z',
    updated_at: '2025-12-01T10:00:00Z',
  },
  {
    id: 'c2',
    full_name: 'Marc Thibault',
    email: 'marc.t@outlook.fr',
    phone: '+33 6 12 34 56 78',
    nationality: 'French',
    is_vip: false,
    is_repeat_client: true,
    created_at: '2025-11-15T09:00:00Z',
    updated_at: '2025-11-15T09:00:00Z',
  },
  {
    id: 'c3',
    full_name: 'Amelia Richardson',
    email: 'amelia.r@btinternet.com',
    phone: '+44 7911 234567',
    nationality: 'British',
    is_vip: false,
    is_repeat_client: false,
    dietary_restrictions: 'Vegetarian',
    created_at: '2026-01-05T08:30:00Z',
    updated_at: '2026-01-05T08:30:00Z',
  },
  {
    id: 'c4',
    full_name: 'Chen Wei',
    company_name: 'Horizon Travel Group',
    email: 'chen.wei@horizontravel.cn',
    phone: '+86 138 0013 8000',
    nationality: 'Chinese',
    is_vip: true,
    is_repeat_client: true,
    notes: 'Corporate client. Books group tours quarterly.',
    created_at: '2025-10-20T11:00:00Z',
    updated_at: '2025-10-20T11:00:00Z',
  },
];

export const mockPartners: Partner[] = [
  {
    id: 'p1',
    company_name: 'Luxury Escapes UK',
    contact_person: 'Sarah Mills',
    email: 'sarah@luxuryescapes.co.uk',
    phone: '+44 20 7946 0321',
    country: 'United Kingdom',
    commission_rate: 12,
    contract_reference: 'LE-SAM-2025',
    is_active: true,
    total_bookings: 24,
    total_commission_earned: 18420,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'p2',
    company_name: 'Horizon Travel Group',
    contact_person: 'Chen Wei',
    email: 'chen.wei@horizontravel.cn',
    phone: '+86 138 0013 8000',
    country: 'China',
    commission_rate: 10,
    contract_reference: 'HT-SAM-2025',
    is_active: true,
    total_bookings: 18,
    total_commission_earned: 12600,
    created_at: '2025-03-15T00:00:00Z',
  },
  {
    id: 'p3',
    company_name: 'Voyages Lumière',
    contact_person: 'Pierre Dubois',
    email: 'p.dubois@voyageslumiere.fr',
    phone: '+33 1 42 68 53 00',
    country: 'France',
    commission_rate: 11,
    is_active: true,
    total_bookings: 9,
    total_commission_earned: 7350,
    created_at: '2025-06-01T00:00:00Z',
  },
];

export const mockReservations: Reservation[] = [
  {
    id: 'r1',
    reference: 'SAM-2026-0041',
    status: 'confirmed',
    client_id: 'c1',
    client: mockClients[0],
    partner_id: 'p1',
    partner: mockPartners[0],
    partner_reference: 'LE-88432',
    travel_purpose: 'honeymoon',
    arrival_date: '2026-04-18',
    departure_date: '2026-04-28',
    num_adults: 2,
    num_children: 0,
    num_infants: 0,
    destinations: ['Galle', 'Mirissa', 'Tangalle'],
    flight_arrival: 'EK651',
    airport_arrival: 'Bandaranaike International Airport',
    budget_range: '£6,000 – £8,000',
    currency: 'GBP',
    total_cost: 7400,
    total_paid: 3700,
    commission_amount: 888,
    payment_status: 'partial',
    assigned_staff: 'Nimsha',
    is_vip: true,
    special_occasions: ['honeymoon'],
    internal_notes: 'Honeymoon couple. Arrange rose petals & champagne on arrival.',
    created_at: '2026-02-10T10:00:00Z',
    updated_at: '2026-03-15T14:30:00Z',
  },
  {
    id: 'r2',
    reference: 'SAM-2026-0042',
    status: 'enquiry',
    client_id: 'c2',
    client: mockClients[1],
    travel_purpose: 'leisure',
    arrival_date: '2026-05-03',
    departure_date: '2026-05-10',
    num_adults: 1,
    num_children: 0,
    num_infants: 0,
    destinations: ['Ella', 'Kandy'],
    budget_range: '€3,000 – €4,500',
    currency: 'EUR',
    total_cost: 0,
    total_paid: 0,
    commission_amount: 0,
    payment_status: 'pending',
    is_vip: false,
    created_at: '2026-04-01T09:15:00Z',
    updated_at: '2026-04-01T09:15:00Z',
  },
  {
    id: 'r3',
    reference: 'SAM-2026-0043',
    status: 'trip_active',
    client_id: 'c4',
    client: mockClients[3],
    partner_id: 'p2',
    partner: mockPartners[1],
    travel_purpose: 'group_tour',
    arrival_date: '2026-04-06',
    departure_date: '2026-04-15',
    num_adults: 12,
    num_children: 0,
    num_infants: 0,
    destinations: ['Sigiriya', 'Kandy', 'Galle', 'Colombo'],
    currency: 'USD',
    total_cost: 28800,
    total_paid: 28800,
    commission_amount: 2880,
    payment_status: 'paid',
    assigned_staff: 'Nimsha',
    is_vip: true,
    internal_notes: 'Group of 12 corporate clients. VIP transfers arranged.',
    created_at: '2026-01-20T08:00:00Z',
    updated_at: '2026-04-06T07:30:00Z',
  },
  {
    id: 'r4',
    reference: 'SAM-2026-0044',
    status: 'invoice_sent',
    client_id: 'c3',
    client: mockClients[2],
    travel_purpose: 'leisure',
    arrival_date: '2026-05-12',
    departure_date: '2026-05-20',
    num_adults: 2,
    num_children: 0,
    num_infants: 0,
    destinations: ['Galle', 'Weligama'],
    currency: 'GBP',
    total_cost: 4200,
    total_paid: 0,
    commission_amount: 0,
    payment_status: 'pending',
    assigned_staff: 'Nimsha',
    is_vip: false,
    created_at: '2026-03-28T11:00:00Z',
    updated_at: '2026-04-05T16:00:00Z',
  },
  {
    id: 'r5',
    reference: 'SAM-2026-0045',
    status: 'completed',
    client_id: 'c2',
    client: mockClients[1],
    travel_purpose: 'leisure',
    arrival_date: '2026-03-10',
    departure_date: '2026-03-17',
    num_adults: 1,
    num_children: 0,
    num_infants: 0,
    destinations: ['The South'],
    currency: 'EUR',
    total_cost: 3800,
    total_paid: 3800,
    commission_amount: 0,
    payment_status: 'paid',
    is_vip: false,
    created_at: '2026-01-15T10:00:00Z',
    updated_at: '2026-03-18T09:00:00Z',
  },
];

export const mockSuppliers: Supplier[] = [
  // ── Hotels ────────────────────────────────────────────────────────────────
  {
    id: 's1',
    name: 'Amangalla',
    type: 'hotel',
    status: 'active',
    contact_person: 'Priyanka Jayawardena',
    email: 'reservations@amangalla.com',
    phone: '+94 91 223 3388',
    whatsapp: '+94 77 223 3388',
    website: 'https://www.aman.com/resorts/amangalla',
    destinations: ['Galle'],
    address: 'Church Street, Fort, Galle 80000, Sri Lanka',
    country: 'Sri Lanka',
    currency: 'USD',
    payment_terms: 'net_30',
    contract_reference: 'SAM-AGA-2026',
    contract_start: '2026-01-01',
    contract_end: '2026-12-31',
    cancellation_policy: '72-hour policy. 100% charge if cancelled within 72 hours of arrival.',
    rating: 5,
    total_bookings: 34,
    notes: 'Historic property within Galle Fort. Best suites: Garden Room, The Gallery Suite. Excellent for honeymoon packages. Coordinate directly with Priyanka for VIP requests.',
    rates: [
      { id: 'sr1a', service: 'Garden Room (BB)', unit: 'per_room', cost: 620, currency: 'USD', season: 'off_peak' },
      { id: 'sr1b', service: 'Garden Room (BB) — Peak', unit: 'per_room', cost: 950, currency: 'USD', season: 'peak', valid_from: '2026-12-15', valid_to: '2027-01-15' },
      { id: 'sr1c', service: 'The Gallery Suite (BB)', unit: 'per_room', cost: 1250, currency: 'USD', season: 'all' },
    ],
    bank_name: 'Hatton National Bank',
    bank_account: 'HNB-0082-1234-5678',
    swift_code: 'HATNSLLX',
    created_at: '2025-01-15T00:00:00Z',
  },
  {
    id: 's2',
    name: 'Amanwella',
    type: 'hotel',
    status: 'active',
    contact_person: 'Kavindra Silva',
    email: 'reservations@amanwella.com',
    phone: '+94 47 224 1333',
    destinations: ['Tangalle'],
    address: 'Bodhi Mawatha, Tangalle 82200, Sri Lanka',
    country: 'Sri Lanka',
    currency: 'USD',
    payment_terms: 'net_30',
    contract_reference: 'SAM-AWA-2026',
    contract_start: '2026-01-01',
    contract_end: '2026-12-31',
    cancellation_policy: '72-hour policy. Full charge within 72 hours of arrival.',
    rating: 4.9,
    total_bookings: 22,
    notes: 'Clifftop infinity pool. Exclusive beach access. Ideal for honeymoon and luxury leisure. Request cliffside suites for best views.',
    rates: [
      { id: 'sr2a', service: 'Suite (BB)', unit: 'per_room', cost: 720, currency: 'USD', season: 'off_peak' },
      { id: 'sr2b', service: 'Suite (BB) — Peak', unit: 'per_room', cost: 1050, currency: 'USD', season: 'peak', valid_from: '2026-12-15', valid_to: '2027-01-15' },
      { id: 'sr2c', service: 'Beach Villa (BB)', unit: 'per_room', cost: 1400, currency: 'USD', season: 'all' },
    ],
    bank_name: 'Commercial Bank of Ceylon',
    bank_account: 'COM-4421-9900-1122',
    swift_code: 'CCEYLKLX',
    created_at: '2025-01-20T00:00:00Z',
  },
  {
    id: 's3',
    name: 'Wild Coast Tented Lodge',
    type: 'hotel',
    status: 'active',
    contact_person: 'Ravindu Perera',
    email: 'reservations@wildcoastlodge.com',
    phone: '+94 47 567 1234',
    destinations: ['Yala'],
    address: 'Yala National Park Buffer Zone, Palatupana, Sri Lanka',
    country: 'Sri Lanka',
    currency: 'USD',
    payment_terms: 'prepaid',
    contract_reference: 'SAM-WCL-2026',
    contract_start: '2026-01-01',
    contract_end: '2026-12-31',
    cancellation_policy: '14-day policy. 50% charge 8–14 days before arrival. 100% within 7 days.',
    rating: 4.8,
    total_bookings: 18,
    notes: 'Luxury tented camp bordering Yala National Park. All-inclusive including game drives. Minimum 2-night stay. Leopard sightings frequent.',
    rates: [
      { id: 'sr3a', service: 'Tented Suite (All-Inclusive)', unit: 'per_room', cost: 1200, currency: 'USD', season: 'all', notes: 'Includes 3 game drives, all meals and beverages' },
    ],
    bank_name: 'Sampath Bank',
    bank_account: 'SPB-7762-3344-9988',
    created_at: '2025-03-01T00:00:00Z',
  },
  {
    id: 's4',
    name: 'Elephant Corridor',
    type: 'hotel',
    status: 'active',
    contact_person: 'Nishantha Bandara',
    email: 'info@elephantcorridor.com',
    phone: '+94 66 228 4949',
    destinations: ['Sigiriya', 'Dambulla'],
    address: 'Giritale Road, Sigiriya, Sri Lanka',
    country: 'Sri Lanka',
    currency: 'USD',
    payment_terms: 'net_15',
    contract_reference: 'SAM-ECH-2026',
    contract_start: '2026-01-01',
    contract_end: '2026-12-31',
    cancellation_policy: '48-hour policy. First night charged if cancelled within 48 hours.',
    rating: 4.6,
    total_bookings: 29,
    notes: 'Stunning villa rooms with private pools overlooking the Sigiriya forest. Elephant sightings at dusk. Excellent base for the Cultural Triangle.',
    rates: [
      { id: 'sr4a', service: 'Deluxe Villa (BB)', unit: 'per_room', cost: 340, currency: 'USD', season: 'off_peak' },
      { id: 'sr4b', service: 'Deluxe Villa (BB) — Peak', unit: 'per_room', cost: 480, currency: 'USD', season: 'peak' },
      { id: 'sr4c', service: 'Infinity Suite (BB)', unit: 'per_room', cost: 560, currency: 'USD', season: 'all' },
    ],
    created_at: '2025-02-10T00:00:00Z',
  },
  // ── Transport ─────────────────────────────────────────────────────────────
  {
    id: 's5',
    name: 'Aero Lanka Transfers',
    type: 'transport',
    status: 'active',
    contact_person: 'Saman Dissanayake',
    email: 'bookings@aerolanka.lk',
    phone: '+94 77 888 1234',
    whatsapp: '+94 77 888 1234',
    destinations: ['Colombo', 'Galle', 'Mirissa', 'Tangalle', 'Ella', 'Sigiriya', 'Kandy', 'Nuwara Eliya', 'Yala'],
    address: '15 Braybrooke Place, Colombo 02, Sri Lanka',
    country: 'Sri Lanka',
    currency: 'USD',
    payment_terms: 'net_15',
    contract_reference: 'SAM-ALT-2026',
    contract_start: '2026-01-01',
    contract_end: '2026-12-31',
    cancellation_policy: '24-hour policy. No charge if cancelled more than 24 hours before pickup.',
    rating: 4.7,
    total_bookings: 87,
    notes: 'Reliable nationwide fleet. English-speaking drivers. GPS-tracked vehicles. Available 24/7. Best choice for airport transfers and inter-city routes.',
    rates: [
      { id: 'sr5a', service: 'CMB Airport — Colombo City (Sedan)', unit: 'per_vehicle', cost: 35, currency: 'USD', season: 'all' },
      { id: 'sr5b', service: 'CMB Airport — Galle (Sedan)', unit: 'per_vehicle', cost: 95, currency: 'USD', season: 'all' },
      { id: 'sr5c', service: 'CMB Airport — Ella (KDH Van)', unit: 'per_vehicle', cost: 185, currency: 'USD', season: 'all' },
      { id: 'sr5d', service: 'Intra-City Half-Day (Sedan)', unit: 'per_vehicle', cost: 55, currency: 'USD', season: 'all' },
      { id: 'sr5e', service: 'Full-Day Island Tour (Luxury SUV)', unit: 'per_vehicle', cost: 145, currency: 'USD', season: 'all' },
    ],
    bank_name: 'Bank of Ceylon',
    bank_account: 'BOC-1100-2233-4455',
    swift_code: 'BCEYLKLX',
    created_at: '2025-01-05T00:00:00Z',
  },
  {
    id: 's6',
    name: 'Royal Lanka Chauffeurs',
    type: 'transport',
    status: 'active',
    contact_person: 'Ruwan Jayasekara',
    email: 'ruwan@royallanka.com',
    phone: '+94 71 445 6789',
    whatsapp: '+94 71 445 6789',
    destinations: ['Colombo', 'Galle', 'Mirissa', 'Tangalle', 'Weligama'],
    country: 'Sri Lanka',
    currency: 'USD',
    payment_terms: 'net_7',
    contract_reference: 'SAM-RLC-2026',
    contract_start: '2026-01-01',
    contract_end: '2026-10-31',
    cancellation_policy: '12-hour cancellation policy. Charge applies within 12 hours of pickup.',
    rating: 4.5,
    total_bookings: 44,
    notes: 'Boutique operator specialising in south coast routes. Very personal service. Complimentary coconut water on collection. Ruwan speaks excellent English.',
    rates: [
      { id: 'sr6a', service: 'CMB Airport — Galle (Luxury Sedan)', unit: 'per_vehicle', cost: 110, currency: 'USD', season: 'all' },
      { id: 'sr6b', service: 'CMB Airport — Weligama (Luxury Sedan)', unit: 'per_vehicle', cost: 125, currency: 'USD', season: 'all' },
      { id: 'sr6c', service: 'Full-Day South Coast (Luxury SUV)', unit: 'per_vehicle', cost: 200, currency: 'USD', season: 'all' },
    ],
    created_at: '2025-04-01T00:00:00Z',
  },
  // ── Activities ────────────────────────────────────────────────────────────
  {
    id: 's7',
    name: 'Deep Blue Dive & Whale Watch',
    type: 'activity',
    status: 'active',
    contact_person: 'Dinesh Amarasinghe',
    email: 'deepblue@mirissa.lk',
    phone: '+94 77 334 5678',
    whatsapp: '+94 77 334 5678',
    destinations: ['Mirissa'],
    address: 'Mirissa Beach, Matara District, Sri Lanka',
    country: 'Sri Lanka',
    currency: 'USD',
    payment_terms: 'prepaid',
    contract_reference: 'SAM-DBW-2026',
    contract_start: '2026-01-01',
    contract_end: '2026-12-31',
    cancellation_policy: 'Full refund for weather cancellations. 48-hour notice required otherwise.',
    rating: 4.8,
    total_bookings: 56,
    notes: 'Best whale watching November–April. Blue whales common January–March. Spinner dolphin encounters nearly daily. Government-licensed vessel.',
    rates: [
      { id: 'sr7a', service: 'Whale Watching (3–4 hrs, shared)', unit: 'per_person', cost: 45, currency: 'USD', season: 'all' },
      { id: 'sr7b', service: 'Whale Watching (Private Boat)', unit: 'per_group', cost: 350, currency: 'USD', season: 'all', notes: 'Up to 8 persons' },
      { id: 'sr7c', service: 'Snorkelling Half-Day', unit: 'per_person', cost: 38, currency: 'USD', season: 'all' },
    ],
    created_at: '2025-02-15T00:00:00Z',
  },
  {
    id: 's8',
    name: 'Lanka Heritage Tours',
    type: 'activity',
    status: 'active',
    contact_person: 'Prasad Rajapaksa',
    email: 'prasad@lankaheritagetours.com',
    phone: '+94 66 224 7890',
    destinations: ['Sigiriya', 'Dambulla', 'Polonnaruwa', 'Anuradhapura'],
    country: 'Sri Lanka',
    currency: 'USD',
    payment_terms: 'net_15',
    contract_reference: 'SAM-LHT-2026',
    contract_start: '2026-01-01',
    contract_end: '2026-12-31',
    cancellation_policy: '24-hour cancellation. No charge if cancelled 24 hours in advance.',
    rating: 4.6,
    total_bookings: 38,
    notes: 'Specialist in UNESCO Cultural Triangle sites. Government-certified guides. Entrance fees included in quoted prices.',
    rates: [
      { id: 'sr8a', service: 'Sigiriya Rock Fortress (guided)', unit: 'per_person', cost: 65, currency: 'USD', season: 'all', notes: 'Includes entrance fee' },
      { id: 'sr8b', service: 'Cultural Triangle Full Day', unit: 'per_group', cost: 280, currency: 'USD', season: 'all', notes: 'Sigiriya + Dambulla Cave Temple, up to 6 pax, includes entrances' },
      { id: 'sr8c', service: 'Polonnaruwa Archaeological City', unit: 'per_person', cost: 55, currency: 'USD', season: 'all', notes: 'Includes entrance fee and bicycle hire' },
    ],
    created_at: '2025-03-10T00:00:00Z',
  },
  {
    id: 's9',
    name: 'Ella Hike & Trek',
    type: 'activity',
    status: 'active',
    contact_person: 'Chamara Bandara',
    email: 'chamara@ellahike.lk',
    phone: '+94 55 222 8877',
    whatsapp: '+94 77 222 8877',
    destinations: ['Ella'],
    country: 'Sri Lanka',
    currency: 'USD',
    payment_terms: 'prepaid',
    contract_reference: 'SAM-EHT-2026',
    contract_start: '2026-01-01',
    contract_end: '2026-12-31',
    cancellation_policy: 'Full refund for weather cancellations. 24-hour notice required otherwise.',
    rating: 4.4,
    total_bookings: 24,
    notes: "Specialises in Little Adam's Peak and Ella Rock. Early morning departures recommended. Tea estate visits included in full-day packages.",
    rates: [
      { id: 'sr9a', service: "Little Adam's Peak Guided Hike", unit: 'per_person', cost: 28, currency: 'USD', season: 'all' },
      { id: 'sr9b', service: 'Ella Rock Full-Day Hike', unit: 'per_person', cost: 42, currency: 'USD', season: 'all', notes: 'Includes lunch and tea plantation visit' },
      { id: 'sr9c', service: 'Nine Arches Bridge & Surrounds', unit: 'per_group', cost: 85, currency: 'USD', season: 'all', notes: 'Up to 4 persons, 3 hours' },
    ],
    created_at: '2025-05-01T00:00:00Z',
  },
  // ── Guides ────────────────────────────────────────────────────────────────
  {
    id: 's10',
    name: 'Chaminda Perera',
    type: 'guide',
    status: 'active',
    contact_person: 'Chaminda Perera',
    email: 'chaminda.guide@gmail.com',
    phone: '+94 77 556 2233',
    whatsapp: '+94 77 556 2233',
    destinations: ['Colombo', 'Galle', 'Kandy', 'Sigiriya', 'Ella', 'Nuwara Eliya'],
    country: 'Sri Lanka',
    currency: 'USD',
    payment_terms: 'net_7',
    rating: 4.9,
    total_bookings: 62,
    notes: 'Government-licensed chauffeur guide. Languages: English, French. 18 years experience. Specialises in cultural and wildlife itineraries. Highly recommended for VIP clients.',
    rates: [
      { id: 'sr10a', service: 'Full Day Guiding (excl. transport)', unit: 'per_person', cost: 95, currency: 'USD', season: 'all', notes: 'Own vehicle available at additional cost' },
      { id: 'sr10b', service: 'Half Day (up to 5 hrs)', unit: 'per_group', cost: 65, currency: 'USD', season: 'all' },
      { id: 'sr10c', service: 'Multi-Day Rate (3+ consecutive days)', unit: 'per_person', cost: 80, currency: 'USD', season: 'all', notes: 'Discounted daily rate' },
    ],
    created_at: '2025-01-20T00:00:00Z',
  },
  {
    id: 's11',
    name: 'Saman Fernando',
    type: 'guide',
    status: 'active',
    contact_person: 'Saman Fernando',
    email: 'saman.tourguide@gmail.com',
    phone: '+94 71 782 4455',
    whatsapp: '+94 71 782 4455',
    destinations: ['Colombo', 'Kandy', 'Nuwara Eliya', 'Dambulla', 'Sigiriya', 'Polonnaruwa'],
    country: 'Sri Lanka',
    currency: 'USD',
    payment_terms: 'net_7',
    rating: 4.7,
    total_bookings: 41,
    notes: 'Languages: English, German. Specialises in tea country and Cultural Triangle. Excellent knowledge of local cuisine and cultural etiquette. Very reliable.',
    rates: [
      { id: 'sr11a', service: 'Full Day Guiding', unit: 'per_person', cost: 85, currency: 'USD', season: 'all' },
      { id: 'sr11b', service: 'Half Day (up to 5 hrs)', unit: 'per_group', cost: 55, currency: 'USD', season: 'all' },
    ],
    created_at: '2025-02-28T00:00:00Z',
  },
  // ── Restaurants ───────────────────────────────────────────────────────────
  {
    id: 's12',
    name: 'Fort Bazaar Restaurant',
    type: 'restaurant',
    status: 'active',
    contact_person: 'Nimali Wickramasinghe',
    email: 'events@fortbazaar.lk',
    phone: '+94 91 438 0000',
    website: 'https://www.fortbazaar.com',
    destinations: ['Galle'],
    address: '26 Church Street, Fort, Galle, Sri Lanka',
    country: 'Sri Lanka',
    currency: 'USD',
    payment_terms: 'prepaid',
    contract_reference: 'SAM-FBR-2026',
    contract_start: '2026-01-01',
    contract_end: '2026-12-31',
    cancellation_policy: '48-hour cancellation for group bookings. 4-hour notice for individual covers.',
    rating: 4.5,
    total_bookings: 16,
    notes: 'Heritage boutique hotel restaurant inside Galle Fort. Excellent for welcome or farewell group dinners. Semi-private dining room accommodates up to 20 guests.',
    rates: [
      { id: 'sr12a', service: 'Set Dinner Menu (3 courses)', unit: 'per_person', cost: 48, currency: 'USD', season: 'all' },
      { id: 'sr12b', service: 'Private Dining Room (min 10 pax)', unit: 'per_group', cost: 380, currency: 'USD', season: 'all', notes: '3-course menu + selected beverages' },
    ],
    created_at: '2025-06-01T00:00:00Z',
  },
];

export const mockItineraries: Itinerary[] = [
  {
    id: 'itin-r1',
    reservation_id: 'r1',
    version: 1,
    status: 'draft',
    title: 'James & Sophie Whitfield — Sri Lanka Honeymoon',
    created_at: '2026-02-15T10:00:00Z',
    updated_at: '2026-02-15T10:00:00Z',
    days: [
      {
        id: 'r1-d1',
        day_number: 1,
        date: '2026-04-18',
        title: 'Arrival & Transfer to Galle',
        narrative: 'Your journey begins as you arrive at Bandaranaike International Airport. Your Samsara representative will meet you in the arrivals hall with a name board and escort you on a scenic coastal drive south to the historic Galle Fort, where your boutique hotel awaits.',
        meals: { breakfast: false, lunch: false, dinner: false },
        items: [
          {
            id: 'r1-d1-i1',
            type: 'flight',
            time: '21:45',
            title: 'Arrive Colombo — EK651',
            description: 'Emirates flight from Dubai. Samsara representative meets you in arrivals hall with name board.',
            supplier_name: '',
            duration_minutes: 0,
            confirmation_ref: 'EK651',
            included: true,
            internal_notes: 'Flight lands on time. Arrange welcome sign with Whitfield name.',
          },
          {
            id: 'r1-d1-i2',
            type: 'transfer',
            time: '22:30',
            title: 'Airport Transfer to Jetwing Lighthouse, Galle',
            description: 'Private air-conditioned vehicle. Scenic coastal highway drive. Approximately 2 hours 30 minutes.',
            supplier_name: 'Samsara Transport',
            duration_minutes: 150,
            confirmation_ref: 'TRANS-001',
            included: true,
            internal_notes: 'Driver: Ruwan (+94 77 112 3344). AC Toyota Land Cruiser confirmed.',
          },
          {
            id: 'r1-d1-i3',
            type: 'accommodation',
            time: '',
            title: 'Jetwing Lighthouse — Check-in',
            description: 'Superior Ocean View Room. Complimentary late-arrival welcome drink. Luggage assistance provided.',
            supplier_name: 'Jetwing Lighthouse',
            duration_minutes: 0,
            confirmation_ref: 'JL-88432',
            included: true,
            internal_notes: 'Request rooms 302 or 304 — best ocean views. Arrange rose petal turndown + champagne for honeymoon couple. Confirm late arrival with hotel.',
          },
        ],
      },
      {
        id: 'r1-d2',
        day_number: 2,
        date: '2026-04-19',
        title: 'Galle Fort Exploration',
        narrative: 'Spend the morning exploring the enchanting Galle Fort, a UNESCO World Heritage Site. Wander cobblestone streets flanked by 400 years of Dutch colonial architecture, browse boutique galleries and artisan workshops, and soak in the atmosphere from the ancient rampart walls.',
        meals: { breakfast: true, lunch: false, dinner: true },
        items: [
          {
            id: 'r1-d2-i1',
            type: 'meal',
            time: '07:30',
            title: 'Breakfast — Jetwing Lighthouse',
            description: 'Full tropical breakfast buffet. Panoramic ocean views from the terrace.',
            supplier_name: 'Jetwing Lighthouse',
            duration_minutes: 0,
            confirmation_ref: '',
            included: true,
            internal_notes: '',
          },
          {
            id: 'r1-d2-i2',
            type: 'guide',
            time: '09:00',
            title: 'Private Galle Fort Walking Tour',
            description: 'Expert local guide leads a 3-hour immersive tour through the fort\'s Dutch Reformed Church, lighthouse, rampart walls, clock tower, and artisan boutiques.',
            supplier_name: 'Guide: Pradeep Silva',
            duration_minutes: 180,
            confirmation_ref: 'GUIDE-PS-0419',
            included: true,
            internal_notes: 'Pradeep speaks excellent French. Confirm language preference with clients before tour.',
          },
          {
            id: 'r1-d2-i3',
            type: 'free_time',
            time: '12:30',
            title: 'Leisure Afternoon — Dutch Hospital & Ramparts',
            description: 'Free time to explore the Dutch Hospital shopping precinct, browse local boutiques, or enjoy sunset drinks from the iconic fort ramparts.',
            supplier_name: '',
            duration_minutes: 0,
            confirmation_ref: '',
            included: true,
            internal_notes: '',
          },
          {
            id: 'r1-d2-i4',
            type: 'meal',
            time: '19:30',
            title: 'Dinner — Fort Printers Restaurant',
            description: 'Romantic candlelit dinner at one of Galle\'s finest heritage restaurants, set within a beautifully restored Dutch colonial mansion.',
            supplier_name: 'Fort Printers',
            duration_minutes: 120,
            confirmation_ref: 'FP-RES-0419',
            included: true,
            internal_notes: 'Honeymoon table decoration requested. Confirm reservation and special setup with Fort Printers directly.',
          },
        ],
      },
      {
        id: 'r1-d3',
        day_number: 3,
        date: '2026-04-20',
        title: 'Whale Watching & Move to Mirissa',
        narrative: 'Rise early for one of Sri Lanka\'s most unforgettable experiences — blue whale watching in the deep waters off the southern coast. Afterwards, check in to your beachfront retreat in Mirissa.',
        meals: { breakfast: true, lunch: false, dinner: true },
        items: [
          {
            id: 'r1-d3-i1',
            type: 'meal',
            time: '05:30',
            title: 'Early Breakfast — Jetwing Lighthouse',
            description: 'Light breakfast or packed box served early for whale watching departure.',
            supplier_name: 'Jetwing Lighthouse',
            duration_minutes: 0,
            confirmation_ref: '',
            included: true,
            internal_notes: 'Request packed breakfast box from hotel the night before.',
          },
          {
            id: 'r1-d3-i2',
            type: 'transfer',
            time: '06:00',
            title: 'Transfer Galle → Mirissa Harbour',
            description: 'Private vehicle to Mirissa harbour. Approximately 1 hour.',
            supplier_name: 'Samsara Transport',
            duration_minutes: 60,
            confirmation_ref: 'TRANS-002',
            included: true,
            internal_notes: 'Driver: Ruwan. Depart Jetwing Lighthouse at 06:00 sharp.',
          },
          {
            id: 'r1-d3-i3',
            type: 'activity',
            time: '07:00',
            title: 'Blue Whale Watching — Mirissa',
            description: 'Guided whale-watching excursion into the Indian Ocean. Prime season for blue whales (world\'s largest animal), sperm whales, and spinner dolphin pods. Includes life jackets and light refreshments on board.',
            supplier_name: 'Raja & The Whales',
            duration_minutes: 240,
            confirmation_ref: '',
            included: true,
            internal_notes: 'Book shared boat (private charter available at extra cost). Confirm with Raja & The Whales. Bring seasickness tablets for clients.',
          },
          {
            id: 'r1-d3-i4',
            type: 'accommodation',
            time: '13:00',
            title: 'The Secret Garden Mirissa — Check-in',
            description: 'Garden Suite with private plunge pool. 3 nights. Steps from the beach.',
            supplier_name: 'The Secret Garden Mirissa',
            duration_minutes: 0,
            confirmation_ref: 'SGM-2026-WF',
            included: true,
            internal_notes: 'Honeymoon decoration in room requested. Fruit basket + sparkling wine arranged.',
          },
          {
            id: 'r1-d3-i5',
            type: 'meal',
            time: '19:00',
            title: 'Dinner — Secret Garden Restaurant',
            description: 'Fresh Sri Lankan seafood dinner. Included in room package.',
            supplier_name: 'The Secret Garden Mirissa',
            duration_minutes: 0,
            confirmation_ref: '',
            included: true,
            internal_notes: '',
          },
        ],
      },
      {
        id: 'r1-d4',
        day_number: 4,
        date: '2026-04-21',
        title: 'Mirissa Beach & Snorkelling',
        narrative: 'A perfect beach day on one of Sri Lanka\'s most beautiful crescent bays. Snorkel in the warm coral gardens, or simply relax with a good book while the Indian Ocean laps at the shore.',
        meals: { breakfast: true, lunch: true, dinner: false },
        items: [
          {
            id: 'r1-d4-i1',
            type: 'meal',
            time: '08:00',
            title: 'Breakfast — The Secret Garden',
            description: 'Tropical fruit spread, freshly baked bread, egg station, and fresh juice bar.',
            supplier_name: 'The Secret Garden Mirissa',
            duration_minutes: 0,
            confirmation_ref: '',
            included: true,
            internal_notes: '',
          },
          {
            id: 'r1-d4-i2',
            type: 'activity',
            time: '10:00',
            title: 'Snorkelling — Mirissa Bay',
            description: 'Guided snorkelling session in Mirissa\'s colourful coral gardens. Mask, fins, and snorkel provided. Suitable for beginners.',
            supplier_name: 'Ocean Divers Mirissa',
            duration_minutes: 120,
            confirmation_ref: '',
            included: true,
            internal_notes: 'Check if clients are comfortable swimmers. Alternative: glass-bottom boat tour.',
          },
          {
            id: 'r1-d4-i3',
            type: 'meal',
            time: '13:00',
            title: 'Lunch — Zephyr Restaurant',
            description: 'Fresh grilled seafood and Sri Lankan curries served beachside. Included.',
            supplier_name: 'Zephyr Restaurant',
            duration_minutes: 0,
            confirmation_ref: '',
            included: true,
            internal_notes: '',
          },
          {
            id: 'r1-d4-i4',
            type: 'free_time',
            time: '15:00',
            title: 'Afternoon at Leisure',
            description: 'Relax on Mirissa beach. Sunset cocktails on the hotel terrace at 18:00.',
            supplier_name: '',
            duration_minutes: 0,
            confirmation_ref: '',
            included: true,
            internal_notes: '',
          },
        ],
      },
      {
        id: 'r1-d5',
        day_number: 5,
        date: '2026-04-22',
        title: 'Mirissa Free Day',
        narrative: 'A second day to enjoy Mirissa at your own pace. Optional yoga, a sunset catamaran, or simply another day on this stunning beach.',
        meals: { breakfast: true, lunch: false, dinner: false },
        items: [
          {
            id: 'r1-d5-i1',
            type: 'free_time',
            time: '',
            title: 'Day at Leisure — Mirissa',
            description: 'Free time to explore at your own pace. Optional: sunset catamaran cruise (ask your guide), beach yoga, or visit Coconut Tree Hill.',
            supplier_name: '',
            duration_minutes: 0,
            confirmation_ref: '',
            included: true,
            internal_notes: 'Suggest sunset catamaran as optional add-on — approx $60pp.',
          },
        ],
      },
      {
        id: 'r1-d6',
        day_number: 6,
        date: '2026-04-23',
        title: 'Move to Tangalle — Amanwella',
        narrative: 'Journey east along the rugged southern coastline to the secluded luxury of Amanwella, one of Sri Lanka\'s most acclaimed private beach resorts.',
        meals: { breakfast: true, lunch: false, dinner: true },
        items: [
          {
            id: 'r1-d6-i1',
            type: 'transfer',
            time: '11:00',
            title: 'Transfer Mirissa → Amanwella, Tangalle',
            description: 'Coastal drive east. Approximately 1 hour 30 minutes.',
            supplier_name: 'Samsara Transport',
            duration_minutes: 90,
            confirmation_ref: 'TRANS-003',
            included: true,
            internal_notes: '',
          },
          {
            id: 'r1-d6-i2',
            type: 'accommodation',
            time: '13:00',
            title: 'Amanwella Resort — Check-in',
            description: 'Pool Suite with direct beach access. 3 nights.',
            supplier_name: 'Amanwella',
            duration_minutes: 0,
            confirmation_ref: 'AWL-2026-WF',
            included: true,
            internal_notes: 'VIP amenity and honeymoon decoration requested. Confirm with Aman reservations.',
          },
          {
            id: 'r1-d6-i3',
            type: 'meal',
            time: '19:30',
            title: 'Dinner — Amanwella Restaurant',
            description: 'À la carte dinner at the resort\'s open-air restaurant overlooking the ocean.',
            supplier_name: 'Amanwella',
            duration_minutes: 0,
            confirmation_ref: '',
            included: true,
            internal_notes: '',
          },
        ],
      },
      {
        id: 'r1-d7',
        day_number: 7,
        date: '2026-04-24',
        title: 'Tangalle — Beach & Spa',
        narrative: 'A full day to indulge in Amanwella\'s world-class amenities — the infinity pool, private beach, and award-winning spa.',
        meals: { breakfast: true, lunch: false, dinner: true },
        items: [
          {
            id: 'r1-d7-i1',
            type: 'activity',
            time: '10:00',
            title: 'Couples Spa Treatment — Amanwella',
            description: '90-minute couples massage using traditional Ayurvedic techniques. Pre-bookable at the spa.',
            supplier_name: 'Amanwella Spa',
            duration_minutes: 90,
            confirmation_ref: '',
            included: false,
            internal_notes: 'Not included — additional cost approx $300pp. Offer as upgrade.',
          },
          {
            id: 'r1-d7-i2',
            type: 'free_time',
            time: '',
            title: 'Day at Leisure — Amanwella',
            description: 'Enjoy the resort\'s infinity pool, private beach, complimentary kayaks, and snorkelling equipment.',
            supplier_name: '',
            duration_minutes: 0,
            confirmation_ref: '',
            included: true,
            internal_notes: '',
          },
        ],
      },
      {
        id: 'r1-d8',
        day_number: 8,
        date: '2026-04-25',
        title: 'Udawalawe National Park Safari',
        narrative: 'An early start for one of Sri Lanka\'s greatest wildlife experiences — a full-day jeep safari through Udawalawe National Park, home to one of the highest densities of wild elephants in Asia.',
        meals: { breakfast: true, lunch: false, dinner: true },
        items: [
          {
            id: 'r1-d8-i1',
            type: 'transfer',
            time: '05:30',
            title: 'Transfer Amanwella → Udawalawe NP',
            description: 'Private vehicle. Approximately 1 hour 30 minutes.',
            supplier_name: 'Samsara Transport',
            duration_minutes: 90,
            confirmation_ref: 'TRANS-004',
            included: true,
            internal_notes: '',
          },
          {
            id: 'r1-d8-i2',
            type: 'activity',
            time: '07:00',
            title: 'Jeep Safari — Udawalawe National Park',
            description: 'Full-day open-top jeep safari with expert naturalist guide. Excellent sightings of wild elephants, leopards, crocodiles, water buffalo, and 200+ bird species.',
            supplier_name: 'Udawalawe Safari Co.',
            duration_minutes: 480,
            confirmation_ref: '',
            included: true,
            internal_notes: 'Book half-day AM + half-day PM safari for best wildlife sightings. Pack sunscreen and hats for clients.',
          },
          {
            id: 'r1-d8-i3',
            type: 'transfer',
            time: '16:00',
            title: 'Return Transfer → Amanwella',
            description: 'Private vehicle back to Tangalle.',
            supplier_name: 'Samsara Transport',
            duration_minutes: 90,
            confirmation_ref: 'TRANS-004R',
            included: true,
            internal_notes: '',
          },
        ],
      },
      {
        id: 'r1-d9',
        day_number: 9,
        date: '2026-04-26',
        title: 'Tangalle to Colombo',
        narrative: 'A leisurely morning at Amanwella before your journey north to Colombo for a city tour and final night.',
        meals: { breakfast: true, lunch: true, dinner: false },
        items: [
          {
            id: 'r1-d9-i1',
            type: 'transfer',
            time: '10:00',
            title: 'Transfer Amanwella → Colombo',
            description: 'Southern Expressway. Approximately 3 hours.',
            supplier_name: 'Samsara Transport',
            duration_minutes: 180,
            confirmation_ref: 'TRANS-005',
            included: true,
            internal_notes: '',
          },
          {
            id: 'r1-d9-i2',
            type: 'activity',
            time: '14:00',
            title: 'Colombo City Tour',
            description: 'Explore Pettah market, Gangaramaya Temple, Beira Lake, Galle Face Green, and Independence Square with a private guide.',
            supplier_name: 'Guide: Colombo City Tours',
            duration_minutes: 240,
            confirmation_ref: '',
            included: true,
            internal_notes: '',
          },
          {
            id: 'r1-d9-i3',
            type: 'meal',
            time: '13:00',
            title: 'Lunch en Route',
            description: 'Stop at a recommended roadside restaurant for a Sri Lankan rice & curry lunch.',
            supplier_name: '',
            duration_minutes: 0,
            confirmation_ref: '',
            included: true,
            internal_notes: 'Suggest Ministry of Crab or Semonata in Colombo if time permits.',
          },
          {
            id: 'r1-d9-i4',
            type: 'accommodation',
            time: '18:00',
            title: 'Shangri-La Colombo — Check-in',
            description: 'Deluxe Ocean View Room. 1 night.',
            supplier_name: 'Shangri-La Colombo',
            duration_minutes: 0,
            confirmation_ref: 'SLC-2026-WF',
            included: true,
            internal_notes: 'Honeymoon room upgrade requested if available.',
          },
        ],
      },
      {
        id: 'r1-d10',
        day_number: 10,
        date: '2026-04-27',
        title: 'Colombo — Shopping & Farewell Dinner',
        narrative: 'Your final full day in Sri Lanka. Browse Colombo\'s vibrant markets for last-minute gifts, tea, and spices before a memorable farewell dinner.',
        meals: { breakfast: true, lunch: false, dinner: true },
        items: [
          {
            id: 'r1-d10-i1',
            type: 'free_time',
            time: '09:00',
            title: 'Shopping — Colombo City',
            description: 'Browse Odel, House of Fashions, and Barefoot for souvenirs, tea, gems, and batik.',
            supplier_name: '',
            duration_minutes: 0,
            confirmation_ref: '',
            included: true,
            internal_notes: '',
          },
          {
            id: 'r1-d10-i2',
            type: 'meal',
            time: '19:30',
            title: 'Farewell Dinner — Ministry of Crab',
            description: 'Iconic Colombo dining experience in a restored Dutch hospital. Famous for giant Sri Lankan lagoon crabs.',
            supplier_name: 'Ministry of Crab',
            duration_minutes: 120,
            confirmation_ref: '',
            included: true,
            internal_notes: 'Reserve table for 2. Confirm booking closer to date.',
          },
        ],
      },
      {
        id: 'r1-d11',
        day_number: 11,
        date: '2026-04-28',
        title: 'Departure',
        narrative: 'After a leisurely breakfast, your driver will transfer you to the airport for your onward journey. It has been an honour hosting you in Sri Lanka.',
        meals: { breakfast: true, lunch: false, dinner: false },
        items: [
          {
            id: 'r1-d11-i1',
            type: 'transfer',
            time: '04:30',
            title: 'Transfer Hotel → Bandaranaike Airport',
            description: 'Private vehicle for early morning airport departure.',
            supplier_name: 'Samsara Transport',
            duration_minutes: 45,
            confirmation_ref: 'TRANS-006',
            included: true,
            internal_notes: 'Early departure. Arrange hotel packed breakfast for 04:00.',
          },
          {
            id: 'r1-d11-i2',
            type: 'flight',
            time: '08:15',
            title: 'Depart Colombo — EK652',
            description: 'Emirates flight to Dubai. Onward connections as per client\'s own booking.',
            supplier_name: '',
            duration_minutes: 0,
            confirmation_ref: 'EK652',
            included: true,
            internal_notes: '',
          },
        ],
      },
    ],
  },
];

// ─── GUIDES ───────────────────────────────────────────────────────────────────

export const mockGuides: Guide[] = [
  {
    id: 'g1',
    full_name: 'Chaminda Perera',
    languages: ['English', 'French'],
    specializations: ['Cultural', 'Heritage', 'Wildlife'],
    license_number: 'SLG-2021-0341',
    license_expiry: '2027-06-30',
    phone: '+94 77 123 4567',
    whatsapp: '+94 77 123 4567',
    base_location: 'Colombo',
    daily_rate: 85,
    currency: 'USD',
    rating: 4.9,
    is_available: true,
    notes: 'Exceptional with luxury honeymoon clients. Fluent French speaker.',
    created_at: '2022-03-01T00:00:00Z',
  },
  {
    id: 'g2',
    full_name: 'Nalini Fernando',
    languages: ['English', 'German'],
    specializations: ['Adventure', 'Cultural', 'Trekking'],
    license_number: 'SLG-2020-0187',
    license_expiry: '2026-09-15',
    phone: '+94 71 987 6543',
    whatsapp: '+94 71 987 6543',
    base_location: 'Kandy',
    daily_rate: 75,
    currency: 'USD',
    rating: 4.7,
    is_available: true,
    notes: 'Specialist in hill country and cultural triangle routes.',
    created_at: '2021-07-12T00:00:00Z',
  },
  {
    id: 'g3',
    full_name: 'Roshan Jayawardena',
    languages: ['English', 'Mandarin'],
    specializations: ['Wildlife', 'Nature', 'Birdwatching'],
    license_number: 'SLG-2019-0092',
    license_expiry: '2027-03-20',
    phone: '+94 76 555 7890',
    whatsapp: '+94 76 555 7890',
    base_location: 'Yala',
    daily_rate: 90,
    currency: 'USD',
    rating: 4.8,
    is_available: true,
    notes: 'Expert tracker at Yala and Udawalawe. Mandarin-speaking groups preferred.',
    created_at: '2020-01-20T00:00:00Z',
  },
  {
    id: 'g4',
    full_name: 'Priya Wickramasinghe',
    languages: ['English', 'Italian'],
    specializations: ['Cultural', 'Heritage', 'Cuisine'],
    license_number: 'SLG-2022-0455',
    license_expiry: '2028-01-10',
    phone: '+94 70 234 5678',
    base_location: 'Galle',
    daily_rate: 80,
    currency: 'USD',
    rating: 4.6,
    is_available: true,
    notes: 'South coast specialist. Italian language certified.',
    created_at: '2023-02-14T00:00:00Z',
  },
  {
    id: 'g5',
    full_name: 'Dhanuka Silva',
    languages: ['English', 'Russian'],
    specializations: ['Surfing', 'Adventure', 'Whale Watching'],
    license_number: 'SLG-2021-0310',
    license_expiry: '2027-11-30',
    phone: '+94 77 876 5432',
    whatsapp: '+94 77 876 5432',
    base_location: 'Mirissa',
    daily_rate: 70,
    currency: 'USD',
    rating: 4.5,
    is_available: true,
    notes: 'Coastal and marine activities expert. Strong Russian-market network.',
    created_at: '2022-06-01T00:00:00Z',
  },
  {
    id: 'g6',
    full_name: 'Kasun Dissanayake',
    languages: ['English', 'Japanese'],
    specializations: ['Wildlife', 'Birdwatching', 'Nature'],
    license_number: 'SLG-2018-0044',
    license_expiry: '2025-08-01',
    phone: '+94 72 345 6789',
    base_location: 'Wilpattu',
    daily_rate: 85,
    currency: 'USD',
    rating: 4.8,
    is_available: false,
    notes: 'On leave until May 2026. License renewal pending.',
    created_at: '2019-04-10T00:00:00Z',
  },
  {
    id: 'g7',
    full_name: 'Sanjeewa Rathnayake',
    languages: ['English', 'French', 'Spanish'],
    specializations: ['Cuisine', 'Cultural', 'Heritage'],
    license_number: 'SLG-2023-0521',
    license_expiry: '2029-04-30',
    phone: '+94 71 654 3210',
    whatsapp: '+94 71 654 3210',
    base_location: 'Colombo',
    daily_rate: 95,
    currency: 'USD',
    rating: 4.9,
    is_available: true,
    notes: 'Tri-lingual. Luxury and culinary tourism specialist.',
    created_at: '2023-09-01T00:00:00Z',
  },
  {
    id: 'g8',
    full_name: 'Thilini Bandara',
    languages: ['English', 'Hindi'],
    specializations: ['Wellness', 'Cultural', 'Ayurveda'],
    license_number: 'SLG-2022-0399',
    license_expiry: '2028-06-15',
    phone: '+94 76 789 0123',
    whatsapp: '+94 76 789 0123',
    base_location: 'Kandy',
    daily_rate: 75,
    currency: 'USD',
    rating: 4.7,
    is_available: true,
    notes: 'Specialist in wellness retreats and Ayurveda experiences.',
    created_at: '2023-01-05T00:00:00Z',
  },
];

export const mockGuideAssignments: GuideAssignment[] = [
  { id: 'ga1', guide_id: 'g1', reservation_id: 'r1', date_from: '2026-04-18', date_to: '2026-04-28', confirmed: true,  fee_agreed: 935 },
  { id: 'ga2', guide_id: 'g7', reservation_id: 'r1', date_from: '2026-04-18', date_to: '2026-04-20', confirmed: true,  fee_agreed: 285 },
  { id: 'ga3', guide_id: 'g2', reservation_id: 'r2', date_from: '2026-04-10', date_to: '2026-04-17', confirmed: true,  fee_agreed: 600 },
  { id: 'ga4', guide_id: 'g3', reservation_id: 'r3', date_from: '2026-04-20', date_to: '2026-04-26', confirmed: true,  fee_agreed: 540 },
  { id: 'ga5', guide_id: 'g4', reservation_id: 'r4', date_from: '2026-04-05', date_to: '2026-04-12', confirmed: true,  fee_agreed: 640 },
  { id: 'ga6', guide_id: 'g5', reservation_id: 'r5', date_from: '2026-04-18', date_to: '2026-04-23', confirmed: false, fee_agreed: 420 },
  { id: 'ga7', guide_id: 'g8', reservation_id: 'r2', date_from: '2026-04-10', date_to: '2026-04-14', confirmed: true,  fee_agreed: 375 },
  { id: 'ga8', guide_id: 'g3', reservation_id: 'r6', date_from: '2026-04-27', date_to: '2026-04-30', confirmed: false, fee_agreed: 270 },
  { id: 'ga9', guide_id: 'g2', reservation_id: 'r7', date_from: '2026-05-01', date_to: '2026-05-08', confirmed: true,  fee_agreed: 600 },
  { id: 'ga10',guide_id: 'g1', reservation_id: 'r8', date_from: '2026-05-03', date_to: '2026-05-10', confirmed: true,  fee_agreed: 680 },
];

// ─── FLEET ────────────────────────────────────────────────────────────────────

export const mockVehicles: Vehicle[] = [
  {
    id: 'v1',
    type: 'van',
    registration: 'WP-CAM-1234',
    capacity_adults: 10,
    make: 'Toyota',
    model: 'HiAce',
    year: 2022,
    air_conditioned: true,
    owner: 'own_fleet',
    insurance_expiry: '2027-01-15',
    last_service_date: '2026-02-10',
    is_available: true,
    notes: 'Primary airport transfer van. Well maintained.',
  },
  {
    id: 'v2',
    type: 'car',
    registration: 'WP-CAP-5678',
    capacity_adults: 4,
    make: 'Toyota',
    model: 'Land Cruiser Prado',
    year: 2023,
    air_conditioned: true,
    owner: 'own_fleet',
    insurance_expiry: '2027-03-20',
    last_service_date: '2026-03-01',
    is_available: true,
    notes: 'Luxury VIP vehicle. Reserved for premium clients.',
  },
  {
    id: 'v3',
    type: 'minibus',
    registration: 'WP-CAQ-9012',
    capacity_adults: 22,
    make: 'Toyota',
    model: 'Coaster',
    year: 2021,
    air_conditioned: true,
    owner: 'own_fleet',
    insurance_expiry: '2026-11-30',
    last_service_date: '2026-01-20',
    is_available: true,
    notes: 'Group tours. Requires advance booking for >15 pax.',
  },
  {
    id: 'v4',
    type: 'tuk_tuk',
    registration: 'WP-CAR-3456',
    capacity_adults: 3,
    make: 'Bajaj',
    model: 'RE',
    year: 2020,
    air_conditioned: false,
    owner: 'own_fleet',
    insurance_expiry: '2026-08-15',
    last_service_date: '2026-04-01',
    is_available: true,
    notes: 'City tours and short transfers. Popular with guests.',
  },
  {
    id: 'v5',
    type: 'van',
    registration: 'WP-CAS-7890',
    capacity_adults: 8,
    make: 'Micro',
    model: 'Traveller',
    year: 2019,
    air_conditioned: true,
    owner: 'own_fleet',
    insurance_expiry: '2026-06-30',
    last_service_date: '2025-12-15',
    is_available: false,
    notes: 'Currently in service for scheduled maintenance.',
  },
  {
    id: 'v6',
    type: 'coach',
    registration: 'WP-CAT-1234',
    capacity_adults: 42,
    make: 'MAN',
    model: "Lion's Coach",
    year: 2020,
    air_conditioned: true,
    owner: 'sup_s3',
    insurance_expiry: '2027-05-10',
    last_service_date: '2026-02-28',
    is_available: true,
    notes: 'Subcontracted from Lanka Coach Services. Large group tours.',
  },
];

export const mockDrivers: Driver[] = [
  {
    id: 'd1',
    full_name: 'Suresh Kumara',
    phone: '+94 77 111 2233',
    whatsapp: '+94 77 111 2233',
    license_number: 'B-WP-2019-4421',
    license_expiry: '2027-08-31',
    languages: ['English', 'Sinhala'],
    vehicle_id: 'v1',
    rating: 4.8,
    daily_rate: 45,
    currency: 'USD',
    is_available: true,
    notes: 'Primary HiAce driver. Excellent punctuality record.',
    created_at: '2020-03-15T00:00:00Z',
  },
  {
    id: 'd2',
    full_name: 'Bandula Jayasena',
    phone: '+94 71 222 3344',
    whatsapp: '+94 71 222 3344',
    license_number: 'B-WP-2021-8872',
    license_expiry: '2028-02-14',
    languages: ['English', 'Sinhala', 'Tamil'],
    vehicle_id: 'v2',
    rating: 4.9,
    daily_rate: 55,
    currency: 'USD',
    is_available: true,
    notes: 'VIP Land Cruiser driver. Discreet and professional.',
    created_at: '2021-08-01T00:00:00Z',
  },
  {
    id: 'd3',
    full_name: 'Nimal Perera',
    phone: '+94 76 333 4455',
    license_number: 'B-WP-2018-3301',
    license_expiry: '2026-10-20',
    languages: ['English', 'Sinhala'],
    vehicle_id: 'v3',
    rating: 4.6,
    daily_rate: 40,
    currency: 'USD',
    is_available: true,
    notes: 'Coaster minibus driver. Experienced with group tours.',
    created_at: '2019-05-20T00:00:00Z',
  },
  {
    id: 'd4',
    full_name: 'Rohan Fernando',
    phone: '+94 70 444 5566',
    whatsapp: '+94 70 444 5566',
    license_number: 'B-WP-2022-6614',
    license_expiry: '2028-07-01',
    languages: ['English', 'Sinhala'],
    vehicle_id: 'v5',
    rating: 4.7,
    daily_rate: 42,
    currency: 'USD',
    is_available: false,
    notes: 'On standby while v5 is in service.',
    created_at: '2022-11-10T00:00:00Z',
  },
  {
    id: 'd5',
    full_name: 'Gamini Silva',
    phone: '+94 72 555 6677',
    license_number: 'B-WP-2020-5509',
    license_expiry: '2027-04-15',
    languages: ['Sinhala', 'Basic English'],
    vehicle_id: 'v4',
    rating: 4.5,
    daily_rate: 30,
    currency: 'USD',
    is_available: true,
    notes: 'Tuk tuk specialist for city and Galle Fort tours.',
    created_at: '2020-09-01T00:00:00Z',
  },
];

// ─── SUPPLIER BOOKINGS ────────────────────────────────────────────────────────

export const mockSupplierBookings: SupplierBooking[] = [
  {
    id: 'sb1', reservation_id: 'r1', supplier_name: 'Amangalla Hotel',
    service_type: 'room', service_date: '2026-04-18',
    service_description: 'King Heritage Suite, Bed & Breakfast — 2 nights',
    pax_adults: 2, pax_children: 0,
    room_type: 'King Heritage Suite', meal_plan: 'BB',
    confirmation_status: 'confirmed', confirmation_ref: 'AMG-26-0891',
    confirmation_received_at: '2026-02-14T09:30:00Z',
    supplier_cost: 1400, currency: 'USD',
    payment_status: 'deposit_paid', payment_due_date: '2026-04-10',
    cancellation_deadline: '2026-04-08',
    notes: 'Honeymoon turndown requested. Pool villa preferred.',
  },
  {
    id: 'sb2', reservation_id: 'r1', supplier_name: 'Anantara Peace Haven Tangalle',
    service_type: 'room', service_date: '2026-04-20',
    service_description: 'Anantara Pool Suite, Half Board — 4 nights',
    pax_adults: 2, pax_children: 0,
    room_type: 'Anantara Pool Suite', meal_plan: 'HB',
    confirmation_status: 'on_request',
    supplier_cost: 1800, currency: 'USD',
    payment_status: 'unpaid', payment_due_date: '2026-04-05',
    cancellation_deadline: '2026-04-12',
    notes: 'Awaiting confirmation. Requested beachfront suite.',
  },
  {
    id: 'sb3', reservation_id: 'r1', supplier_name: 'Jetwing Yala',
    service_type: 'room', service_date: '2026-04-24',
    service_description: 'Deluxe Safari Suite, Bed & Breakfast — 2 nights',
    pax_adults: 2, pax_children: 0,
    room_type: 'Deluxe Safari Suite', meal_plan: 'BB',
    confirmation_status: 'confirmed', confirmation_ref: 'JWY-2026-0214',
    confirmation_received_at: '2026-02-20T14:00:00Z',
    supplier_cost: 680, currency: 'USD',
    payment_status: 'deposit_paid', payment_due_date: '2026-04-15',
    cancellation_deadline: '2026-04-17',
  },
  {
    id: 'sb4', reservation_id: 'r1', supplier_name: 'Samsara Transport',
    service_type: 'transfer', service_date: '2026-04-18',
    service_description: 'BIA Airport → Amangalla Hotel, Galle (Toyota Land Cruiser)',
    pax_adults: 2, pax_children: 0,
    confirmation_status: 'confirmed', confirmation_ref: 'TRN-r1-001',
    supplier_cost: 65, currency: 'USD',
    payment_status: 'fully_paid',
  },
  {
    id: 'sb5', reservation_id: 'r1', supplier_name: 'Samsara Transport',
    service_type: 'transfer', service_date: '2026-04-20',
    service_description: 'Galle → Anantara Peace Haven, Tangalle (Toyota HiAce)',
    pax_adults: 2, pax_children: 0,
    confirmation_status: 'confirmed', confirmation_ref: 'TRN-r1-002',
    supplier_cost: 90, currency: 'USD',
    payment_status: 'fully_paid',
  },
  {
    id: 'sb6', reservation_id: 'r1', supplier_name: 'Samsara Transport',
    service_type: 'transfer', service_date: '2026-04-24',
    service_description: 'Tangalle → Jetwing Yala Safari Lodge (Land Cruiser)',
    pax_adults: 2, pax_children: 0,
    confirmation_status: 'confirmed', confirmation_ref: 'TRN-r1-003',
    supplier_cost: 110, currency: 'USD',
    payment_status: 'unpaid', payment_due_date: '2026-04-20',
  },
  {
    id: 'sb7', reservation_id: 'r1', supplier_name: 'Samsara Transport',
    service_type: 'transfer', service_date: '2026-04-26',
    service_description: 'Yala → Bandaranaike International Airport (via Colombo)',
    pax_adults: 2, pax_children: 0,
    confirmation_status: 'confirmed', confirmation_ref: 'TRN-r1-004',
    supplier_cost: 175, currency: 'USD',
    payment_status: 'unpaid', payment_due_date: '2026-04-20',
    notes: 'Early 04:00 departure. Arrange packed breakfast.',
  },
  {
    id: 'sb8', reservation_id: 'r1', supplier_name: 'Mirissa Whale Watch Co.',
    service_type: 'activity', service_date: '2026-04-22',
    service_description: 'Blue Whale Watching — 2 Adults',
    pax_adults: 2, pax_children: 0,
    confirmation_status: 'confirmed', confirmation_ref: 'MWW-2026-044',
    confirmation_received_at: '2026-02-18T11:00:00Z',
    supplier_cost: 80, currency: 'USD',
    payment_status: 'fully_paid',
    notes: 'Departure from Mirissa Harbour 06:30.',
  },
  {
    id: 'sb9', reservation_id: 'r1', supplier_name: 'Galle Heritage Tours',
    service_type: 'activity', service_date: '2026-04-19',
    service_description: 'Galle Fort Heritage Walk — 2 Adults',
    pax_adults: 2, pax_children: 0,
    confirmation_status: 'confirmed', confirmation_ref: 'GHT-2026-112',
    supplier_cost: 60, currency: 'USD',
    payment_status: 'fully_paid',
  },
  {
    id: 'sb10', reservation_id: 'r1', supplier_name: 'Hikkaduwa Ocean Sports',
    service_type: 'activity', service_date: '2026-04-20',
    service_description: 'Snorkeling & Glass Bottom Boat — 2 Adults',
    pax_adults: 2, pax_children: 0,
    confirmation_status: 'on_request',
    supplier_cost: 70, currency: 'USD',
    payment_status: 'unpaid', payment_due_date: '2026-04-16',
    notes: 'Weather-dependent. Backup date: Apr 21.',
  },
  {
    id: 'sb11', reservation_id: 'r1', supplier_name: 'Chaminda Perera (Senior Guide)',
    service_type: 'guide', service_date: '2026-04-18',
    service_description: 'Senior Guide Service — 11 days (Apr 18–28)',
    pax_adults: 2, pax_children: 0,
    confirmation_status: 'confirmed', confirmation_ref: 'GDG-r1-001',
    supplier_cost: 935, currency: 'USD',
    payment_status: 'deposit_paid', payment_due_date: '2026-04-25',
    notes: 'Full-tour guide. Includes whale watching & Yala safari accompaniment.',
  },
  {
    id: 'sb12', reservation_id: 'r1', supplier_name: 'Anantara Peace Haven',
    service_type: 'meal', service_date: '2026-04-22',
    service_description: 'Romantic Private Beach Dinner — 2 Adults',
    pax_adults: 2, pax_children: 0,
    confirmation_status: 'confirmed', confirmation_ref: 'APH-MEAL-081',
    supplier_cost: 120, currency: 'USD',
    payment_status: 'fully_paid',
    notes: 'Champagne setup included. Sunset timing approx. 18:15.',
  },
];

// ─── COST LINES ───────────────────────────────────────────────────────────────

export const mockCostLines: CostLine[] = [
  // Accommodation
  { id: 'cl1', reservation_id: 'r1', category: 'accommodation', supplier_name: 'Amangalla Hotel',               description: 'King Heritage Suite, BB',          date: '2026-04-18', pax: 2, unit_cost: 700,  unit_sell: 975,  quantity: 2,  currency: 'USD', included_in_package: false },
  { id: 'cl2', reservation_id: 'r1', category: 'accommodation', supplier_name: 'Anantara Peace Haven Tangalle', description: 'Anantara Pool Suite, HB',           date: '2026-04-20', pax: 2, unit_cost: 450,  unit_sell: 630,  quantity: 4,  currency: 'USD', included_in_package: false },
  { id: 'cl3', reservation_id: 'r1', category: 'accommodation', supplier_name: 'Jetwing Yala',                  description: 'Deluxe Safari Suite, BB',           date: '2026-04-24', pax: 2, unit_cost: 340,  unit_sell: 475,  quantity: 2,  currency: 'USD', included_in_package: false },
  // Transport
  { id: 'cl4', reservation_id: 'r1', category: 'transport', supplier_name: 'Samsara Transport', description: 'BIA Airport → Galle (Land Cruiser)',          date: '2026-04-18', pax: 2, unit_cost: 65,   unit_sell: 100,  quantity: 1,  currency: 'USD', included_in_package: false },
  { id: 'cl5', reservation_id: 'r1', category: 'transport', supplier_name: 'Samsara Transport', description: 'Galle → Tangalle (HiAce Van)',                date: '2026-04-20', pax: 2, unit_cost: 90,   unit_sell: 135,  quantity: 1,  currency: 'USD', included_in_package: false },
  { id: 'cl6', reservation_id: 'r1', category: 'transport', supplier_name: 'Samsara Transport', description: 'Tangalle → Yala (Land Cruiser)',               date: '2026-04-24', pax: 2, unit_cost: 110,  unit_sell: 165,  quantity: 1,  currency: 'USD', included_in_package: false },
  { id: 'cl7', reservation_id: 'r1', category: 'transport', supplier_name: 'Samsara Transport', description: 'Yala → BIA Airport via Colombo',              date: '2026-04-26', pax: 2, unit_cost: 175,  unit_sell: 255,  quantity: 1,  currency: 'USD', included_in_package: false },
  // Activities
  { id: 'cl8',  reservation_id: 'r1', category: 'activity', supplier_name: 'Mirissa Whale Watch Co.',  description: 'Blue Whale Watching',          date: '2026-04-22', pax: 2, unit_cost: 40,  unit_sell: 70,  quantity: 2, currency: 'USD', included_in_package: false },
  { id: 'cl9',  reservation_id: 'r1', category: 'activity', supplier_name: 'Galle Heritage Tours',     description: 'Galle Fort Heritage Walk',     date: '2026-04-19', pax: 2, unit_cost: 30,  unit_sell: 55,  quantity: 2, currency: 'USD', included_in_package: false },
  { id: 'cl10', reservation_id: 'r1', category: 'activity', supplier_name: 'Hikkaduwa Ocean Sports',   description: 'Snorkeling & Glass Bottom Boat',date: '2026-04-20', pax: 2, unit_cost: 35,  unit_sell: 65,  quantity: 2, currency: 'USD', included_in_package: false },
  // Meal
  { id: 'cl11', reservation_id: 'r1', category: 'meal', supplier_name: 'Anantara Peace Haven', description: 'Romantic Private Beach Dinner',         date: '2026-04-22', pax: 2, unit_cost: 120, unit_sell: 195, quantity: 1, currency: 'USD', included_in_package: false },
  // Guide (included in package — no separate sell price)
  { id: 'cl12', reservation_id: 'r1', category: 'guide', supplier_name: 'Chaminda Perera',     description: 'Senior Guide, 11 days (Apr 18–28)',    date: '2026-04-18', pax: 2, unit_cost: 85,  unit_sell: 0,   quantity: 11, currency: 'USD', included_in_package: true  },
  // Misc
  { id: 'cl13', reservation_id: 'r1', category: 'misc', supplier_name: 'Samsara Travel', description: 'Honeymoon Package (flowers, cake, decor)',   date: '2026-04-18', pax: 2, unit_cost: 200, unit_sell: 340, quantity: 1, currency: 'USD', included_in_package: false },
  { id: 'cl14', reservation_id: 'r1', category: 'misc', supplier_name: 'Samsara Travel', description: 'Travel Administration & Planning Fee',       date: '2026-04-18', pax: 2, unit_cost: 0,   unit_sell: 395, quantity: 1, currency: 'USD', included_in_package: false },
];

export const mockStats: DashboardStats = {
  total_reservations: 41,
  active_trips: 3,
  pending_enquiries: 7,
  revenue_this_month: 42600,
  revenue_currency: 'GBP',
  upcoming_arrivals: 5,
  overdue_payments: 1,
  new_enquiries_today: 2,
};
